name: 编译未签名 ipa

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: List Schemes (检查方案名)
        run: |
          xcodebuild -list -project InkReader.xcodeproj

      - name: Build archive
        run: |
          xcodebuild clean archive -project InkReader.xcodeproj -scheme InkReader -sdk iphoneos -configuration Release -archivePath ./build/InkReader.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r ./build/InkReader.xcarchive/Products/Applications/*.app Payload/
          zip -r InkReader.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: InkReader-ipa
          path: InkReader.ipa
